# Generated by Django 5.0.2 on 2024-02-17 13:27

import tumbs.websites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                upload_to=tumbs.websites.models.image.image_upload_path,
                validators=[
                    tumbs.websites.models.image.file_type_validator,
                    tumbs.websites.models.image.file_size_validator,
                ],
                verbose_name="image file",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="website",
            unique_together={("customer_id", "name")},
        ),
    ]
