# Generated by Django 5.0.1 on 2024-02-05 02:43

import tumbs.websites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "image", "verbose_name_plural": "images"},
        ),
        migrations.AlterModelOptions(
            name="page",
            options={"verbose_name": "page", "verbose_name_plural": "pages"},
        ),
        migrations.AlterModelOptions(
            name="website",
            options={"verbose_name": "website", "verbose_name_plural": "websites"},
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(upload_to=tumbs.websites.models.image_upload_path, verbose_name="image file"),
        ),
    ]
