# Generated by Django 5.0.2 on 2024-02-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0002_alter_image_file_alter_website_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="deleted"),
        ),
        migrations.AddField(
            model_name="page",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="deleted"),
        ),
        migrations.AddField(
            model_name="website",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="deleted"),
        ),
    ]
