# Generated by Django 5.0.2 on 2024-02-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0003_image_deleted_page_deleted_website_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="meta",
            field=models.JSONField(blank=True, null=True, verbose_name="meta"),
        ),
    ]
