# Generated by Django 5.0.3 on 2024-03-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0005_website_language_website_region"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="website",
            options={"ordering": ("created",), "verbose_name": "website", "verbose_name_plural": "websites"},
        ),
        migrations.AlterUniqueTogether(
            name="website",
            unique_together=set(),
        ),
    ]
