# Generated by Django 5.0.3 on 2024-03-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0006_alter_website_options_alter_website_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="domain",
            field=models.CharField(blank=True, max_length=255, verbose_name="domain"),
        ),
    ]
