# Generated by Django 5.0.3 on 2024-03-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0007_website_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.JSONField(blank=True, default=list, verbose_name="content"),
        ),
    ]
